services:
  scouterbee:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      GITLAB_TOKEN: ${GITLAB_TOKEN}
      ONEPASSWORD_TOKEN: ${ONEPASSWORD_TOKEN}
      WEBHOOK_URL: ${WEBHOOK_URL}
      HEARTBEAT_URL: ${HEARTBEAT_URL}
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 9.9.9.9
